# Generated by Django 3.0.7 on 2020-06-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200617_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='adress1',
            field=models.CharField(default='adress1', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='adress2',
            field=models.CharField(default='adress2', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='codezip',
            field=models.CharField(default='codezip', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contry',
            field=models.CharField(default='contry', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='discriptions',
            field=models.CharField(default='discriptions', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='phone', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ville',
            field=models.CharField(default='ville', max_length=255),
        ),
    ]
