# Generated by Django 3.0.4 on 2020-05-02 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annonce', '0003_auto_20200502_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonce',
            old_name='categorie',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='annonce',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
